services:
  - type: web
    name: nakayo-corporation
    runtime: php
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generate: true